services:
  - type: web
    name: jobito-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 4000
      - key: JWT_SECRET
        generateValue: true
